language: android
jdk:
    - openjdk7
  # Emulator Management: Create, Start and Wait
branches:
  only:
    - travis-master
before_install:
    - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
before_script:
    - ./wait_for_emulator
    - adb shell input keyevent 82 &
script:
     - TERM=dumb ./gradlew assembleDebug -PdisablePreDex
    #
    # for future use run tests      ./gradlew connectedInstrumentTest
    # all builds and tests          ./gradlew connectedCheck
    # for only debuf                ./gradlew assembleDebug
android:
  components:
    # The BuildTools version used by your project
    - build-tools-22.0.1
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The SDK version used to compile your project
    - android-22
    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22