#!/bin/bash

bootanim=""
failcounter=0
until [[ "$bootanim" =~ "stopped" ]]; do
bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
   echo "$bootanim"
   if [[ "$bootanim" =~ "not found" ]]; then
let "failcounter += 1"
      if [[ $failcounter -gt 3 ]]; then
echo "Pucha!!! Fallamos en iniciar el emulador !!!"
        exit 1
      fi
fi
sleep 1
done
echo "Done"